### ISSUE TITLE
Add support of AzureOpenAiChatModel

### ISSUE THREAD

**Issue by pakamona** [bsorrentino/langgraph4j#50]
Greetings!

First of all, thank you for your implementation and effort! Really appreciate it!

I'm playing around with your code and found that your example of [ChatAgent.java ](https://github.com/bsorrentino/langgraph4j/blob/main/samples/agent-executor/src/main/java/org/bsc/langgraph4j/agentexecutor/actions/CallAgent.java) won't work properly with (at least) `AzureOpenAiChatModel` in case if a tool is called.
Seems like the structure of `AiMessage` is differ for OpenAI (`text` is present) and AzureOpenAI (`text` is nullable if upcoming `ToolExecutionResultMessage` is available) models and hence the `NullPointerException` is thrown.

To reproduce the case I used your test [AgentExecutorTest.java](https://github.com/bsorrentino/langgraph4j/blob/main/samples/agent-executor/src/test/java/org/bsc/langgraph4j/agentexecutor/AgentExecutorTest.java) and just used the following `chatLanguageModel` configuration:

```
var chatLanguageModel = AzureOpenAiChatModel.builder()
                .apiKey("<api_key_goes_here>")
                .deploymentName( "gpt-4o-mini-2024-07-18" )
                .logRequestsAndResponses(true)
                .maxRetries(2)
                .temperature(0.0)
                .maxTokens(2000)
                .build();
```

Stacktrace:
```
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException

	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at org.bsc.async.InternalIterator.next(AsyncGenerator.java:398)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.bsc.langgraph4j.agentexecutor.AgentExecutorTest.executeAgent(AgentExecutorTest.java:69)
	at org.bsc.langgraph4j.agentexecutor.AgentExecutorTest.executeAgentWithSingleToolInvocation(AgentExecutorTest.java:96)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.bsc.langgraph4j.CompiledGraph$AsyncNodeGenerator.next(CompiledGraph.java:548)
	at org.bsc.async.AsyncGenerator$WithEmbed.next(AsyncGenerator.java:99)
	at org.bsc.async.InternalIterator.next(AsyncGenerator.java:396)
	... 12 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/java.util.ImmutableCollections$Map1.<init>(ImmutableCollections.java:1105)
	at java.base/java.util.Map.of(Map.java:1353)
	at org.bsc.langgraph4j.agentexecutor.actions.CallAgent.lambda$apply$1(CallAgent.java:48)
	at org.bsc.langgraph4j.agentexecutor.actions.CallAgent.apply(CallAgent.java:68)
	at org.bsc.langgraph4j.agentexecutor.actions.CallAgent.apply(CallAgent.java:20)
	at org.bsc.langgraph4j.action.AsyncNodeAction.lambda$node_async$0(AsyncNodeAction.java:36)
	at org.bsc.langgraph4j.action.AsyncNodeActionWithConfig.lambda$of$1(AsyncNodeActionWithConfig.java:41)
	at org.bsc.langgraph4j.CompiledGraph$AsyncNodeGenerator.evaluateAction(CompiledGraph.java:452)
	... 15 more
```

**Comment by bsorrentino** [comment]
Hi @pakamona thanks for feedback I'll fix this as soon as possible

**Comment by pakamona** [comment]
Hi @bsorrentino thanks!

**Comment by bsorrentino** [comment]
Hi @pakamona I've fixed the problemi in  [CallAgent](https://github.com/bsorrentino/langgraph4j/blob/develop/samples/agent-executor/src/main/java/org/bsc/langgraph4j/agentexecutor/actions/CallAgent.java) action on `develop`. 

Asap I'll arrange a new official release.

Thank you again for valuable feedback

**Comment by pakamona** [comment]
Hi @bsorrentino thank you for quick turn around and the fix provided! It helped for `AzureOpenAiChatModel` – now it behaves correctly for tool's call case as well. Feel free to work on the release tag.

I have one more conceptual question – your `CallAgent`, `AgentExecutor`, states, serialization stuff from the sample – all of them look like core functionality that would not be changed by default, only in some specific cases. Why aren't they part of the library and need to be recreated in the project? I'm trying to figure out the minimum of required changes so that someone can use your implementation of `langgraph`. For me it seems all of these items are mandatory to be recreated in the project, but it might be you can comment on this?

Thank you in advance!

**Comment by bsorrentino** [comment]
> Hi @bsorrentino thank you for quick turn around and the fix provided! It helped for `AzureOpenAiChatModel` – now it behaves correctly for tool's call case as well. Feel free to work on the release tag.
> 
> I have one more conceptual question – your `CallAgent`, part of `AgentExecutor`, states, serialization stuff from the sample – all of them look like core functionality that would not be changed by default, only in some specific cases. Why aren't they part of the library and need to be recreated in the project? I'm trying to figure out the minimum of required changes so that someone can use your implementation of `langgraph`. For me it seems all of these items are mandatory to be recreated in the project, but it might be you can comment on this?
> 
> What I have – I have a number of different handlers in the application and orchestration made by LLM (prompt + available options). The huge disadvantage of such approach is in the fact that I need to adjust it manually, so there is no any flexibility and condition switch. Also, the LLM's hallicunations may lead do misorchestration. What I want to achieve – I would like to build multi-agent flow so that I describe possible agents to call in the grapth along with assigned tools for specific agent. I expect that decision making on which agent to call will be out of my custom logic.
> 
> Do you think this conversation should be moved to a separate ticket?
> 
> Thank you in advance!

You right @pakamona , the langgraph4j project was born originally  to be part of langchain4j initiative, I've created those use cases to show its usage. Now this project seems walk alone and your idea is well suited in this new strategy. I'll do it 😉
